### ISSUE TITLE
Support for sort order settings

### ISSUE THREAD

**Issue by mrmlnc** [richie5um/vscode-sort-json#1]
Hi, @richie5um!

I love when my code looks good. Everything is so difficult that I wrote a plugin that sorts attributes of the tag.

It would be nice to get a ability to customize the sort order. For example:

```json
{
  "sortJSON.order": ["name", "version", "description", "license", "etc."]
}
```

**before:**

```json
{
  "name": "name",
  "description": "description",
  "version": "version",
  "main": "main",
  "license": "license"
}
```

**after:**

```json
{
  "name": "name",
  "version": "version",
  "description": "description",
  "license": "license",
  "main": "main"
}
```

**Comment by richie5um** [comment]
"that I wrote a plugin that sorts attributes of the tag." <= Cool. What is your plugin called?

I've just added the functionality you requested. If you update to the latest version (1.2.0), and then add the following to your preferences (settings.json):
"sortJSON.orderOverride": ["name", "version", "description"]

Hope it works. Let me know if you have any issues.

-Rich

**Comment by mrmlnc** [comment]
@richie5um, thanks 🙏. The plugin is called [vscode-attrs-sorter](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-attrs-sorter).

**Comment by rafiqkattangere** [comment]
Wish there was a way to sort all but some [like some items I like all time to be on bottom!]

**Comment by richie5um** [comment]
@rafiqkattangere Thanks for the suggestion.

**Comment by richie5um** [comment]
@rafiqkattangere There is now an 'orderUnderride' setting which makes items stay at the bottom.
