### ISSUE TITLE
Support sort by key's length

### ISSUE THREAD

**Issue by clownvary** [richie5um/vscode-sort-json#20]
Can we do a new feature that can allow user sort json data by key's length ?
like this:
origin:
```js
{
name: 'test',
age:20,
otherthings:'xxxxx'
}
```
sorted
```js
{
age:20,
name: 'test',
otherthings:'xxxxx'
}
```
looks so beauty, right？

**Comment by richie5um** [comment]
Done.

Grab latest build (1.13.0), and you now get a command to sort by key length (or, reversed key length).
