### ISSUE TITLE
Feature Request: Sort String arrays

### ISSUE THREAD

**Issue by HaaLeo** [richie5um/vscode-sort-json#24]
# Description
The extension should be capable to sort simple "string-only" arrays as well.

# Example
## Input
```JSON
{
    "MyArray": [
        "b",
        "c",
        "a"
    ],
    "Ahoi": true
}
```

## Expected Output
```JSON
{
    "Ahoi": true,
    "MyArray": [
        "a",
        "b",
        "c"
    ]
}
```

**Comment by tillig** [comment]
Technically this would be a breaking change to the JSON since array order in many cases is important, though if it's off by default it'd be fine.

**Comment by richie5um** [comment]
I think you'd be better selecting the specific array elements and using VS's built in 'Sort lines' command. Trying to add this to SortJSON in a way that made sense and didn't break array order (for those that want to preserve their JSON) seems complex.
