### ISSUE TITLE
Feature Request: Sort alpha-numeric, not lexiconic

### ISSUE THREAD

**Issue by tyler36** [richie5um/vscode-sort-json#26]
This is such a great little extension. I use it daily. 

One little feature request.
Given this ....
```
{
    "list10": "expect 3",
    "list1": "expect 1",
    "list12": "expect 4",
    "list2": "expect 2"
}
```
"Sort JSON" produces this
```
{
    "list1": "expect 1",
    "list10": "expect 3",
    "list12": "expect 4",
    "list2": "expect 2"
}
```
but I want I really want is ...
```
{
    "list1": "expect 1",
    "list2": "expect 2"
    "list10": "expect 3",
    "list12": "expect 4",
}
```

It's one of those annoying little things that makes sense to me but probably is a read pain in the **** to implement. 

Ideally, a config item: ```sortjson.Sort JSON (like a human, not a computer)``` boolean would be great.
Perhaps the name could use some work ;)

**Comment by richie5um** [comment]
Love the idea. Let me see what I can do :)

**Comment by richie5um** [comment]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/907033/60814314-4dd86a00-a18d-11e9-98d8-441b9a5ee4e0.png">

Update to 1.14.0

:)

**Comment by tyler36** [comment]
Wow ... works as requested. Thank you so much! 🎉
