### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by xahon** [richie5um/vscode-sort-json#27]
![o](https://user-images.githubusercontent.com/18731681/61347959-32aede00-a8a2-11e9-9345-00b822cde734.gif)
_The json is selected_

Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic

**Comment by Skuriles** [comment]
Same for we, extension does nothing at all

**Comment by richie5um** [comment]
Thanks for letting me know. Can you send me your JSON file so I can try and repo? I can give you my email if you'd rather not post the JSON publicly.

**Comment by Skuriles** [comment]
I've added a english .json file which doesn't work. Nothing special in it as far as I can see and no json errors.
[en.zip](https://github.com/richie5um/vscode-sort-json/files/3588796/en.zip)

**Comment by richie5um** [comment]
Argh, nuts. Figured it out. If the value contains a ':' colon, it'll fail to sort it. I'll investigate a fix.

Sorry for the (massive) delay.

**Comment by richie5um** [comment]
Updated extension to 1.15.0. Hopefully this resolves your issues

**Comment by Skuriles** [comment]
Thanks. Seems to be fixed!!

**Comment by richie5um** [comment]
Excellent, thanks for letting me know.
