### ISSUE TITLE
Put Objects at end || Sort by length of value

### ISSUE THREAD

**Issue by robsonsobral** [richie5um/vscode-sort-json#28]
Hi! Thank you so much for the extension.

Is it possible to put Numbers and Strings before Objets? Something like sort by the length of the values. It would make easier to analyze a JSON if the short objects came before.

**Comment by richie5um** [comment]
It is possible, but that would make the need for another set of actions. Sorry to say this, but, you are welcome to create a PR with the change.

**Comment by richie5um** [comment]
I've add a sort by type.  Update to v1.17.0

Number < String < Object < Array

Let me know (asap) if you think the order is wrong.
