### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by hiahmedhameed** [richie5um/vscode-sort-json#36]
Hi,

Thank for that nice extension.

Is there a way to bind sorting function with keyboard shortcut ? and how ?

Many thanks.

**Comment by DoganM95** [comment]
You can create your own, just go to File -> Settings -> Keyboard Shortcuts and search for sort json, then assign the shortcuts you need.

There are already many shortcuts existing in vscode, so makes sense the dev did not assign any as there are a lot of sort-json commands available.

**Comment by hiahmedhameed** [comment]
Nice, thanks for the tip.
