### ISSUE TITLE
Publishing this extension on Open VSX

### ISSUE THREAD

**Issue by tywmick** [richie5um/vscode-sort-json#39]
Hello!

I took the liberty of submitting this extension to [Open VSX](https://open-vsx.org/)'s publishing CI (open-vsx/publish-extensions#183), since I was wanting to use it in [VSCodium](https://vscodium.com/). Open VSX is a vendor-neutral open-source registry that can be used by any editor or IDE that supports VS Code extensions, unlike the Visual Studio Marketplace, whose [Terms of Use](https://aka.ms/vsmarketplace-ToU) requires that the Marketplace and any extensions it distributes only be used with Microsoft products.

There's nothing you need to do (once the PR is merged, the CI will build and publish the extension the following night at 03:03 UTC), but I just wanted to give you a heads-up in case you wanted to [claim the `richie5um2` namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access) that'll be created once the extension is published.

Also, if you ever want to take over the publishing of your extension to Open VSX, here are the [publishing instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)—really all it requires is creating an account and adding an <code>[ovsx](https://github.com/eclipse/openvsx/tree/master/cli) publish</code> command in addition to your normal `vsce publish`. And someone would probably have to remove the entry I added to their auto-publishing CI, which I'd be happy to do if you send me a message.

Thanks for making this handy extension!

**Comment by richie5um** [comment]
Awesome. Many thanks.

**Comment by spoenemann** [comment]
Just to clarify: I closed https://github.com/open-vsx/publish-extensions/pull/183 because @richie5um claimed the namespace and so I thought you are going to publish the extension yourself. The `publish-extensions` repository is meant for publishing extensions whose maintainers are either not yet aware of Open VSX or don't want to publish there themselves for any reason.

**Comment by tywmick** [comment]
Oops, I screwed up my explanation, then—my bad! 🤦🏼‍♂️ @richie5um, I completely spaced on the fact that claiming the namespace would prevent the [open-vsx/publish-extensions](https://github.com/open-vsx/publish-extensions) CI from being able to publish it, so are you on board with [grabbing an access token](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) and publishing the extension yourself with [ovsx](https://github.com/eclipse/openvsx/tree/master/cli) in addition to the usual [vsce](https://github.com/microsoft/vscode-vsce) going forward? So sorry for the confusion I've caused.

**Comment by richie5um** [comment]
Sure can. Np :).

**Comment by tywmick** [comment]
Hey, @richie5um, sorry to bug you again about this, but would you mind [publishing this to Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)? 😅 Or if you want to un-claim the namespace (create an issue similar to EclipseFdn/open-vsx.org#161, I assume), I'd be happy to resubmit it to OpenVSX's publishing CI (open-vsx/publish-extensions#183) so you don't have to bother with setting up the publishing script. 👍🏼

**Comment by spoenemann** [comment]
FYI it is not necessary to "unclaim" the namespace, the publishing CI can be used anyway. See the Wiki for more details:
https://github.com/eclipse/openvsx/wiki/Namespace-Access#the-open-vsx-account

**Comment by tywmick** [comment]
Oh, cool! In that case, Rich, nothing to worry about after all—I'll close this case once the CI publishes it 👍🏼

**Comment by richie5um** [comment]
Thanks Ty and Miro. Sorry, I'm super busy at my jobby job, so only just had time to catch-up on this thread. Seems like I don't need to do anything though, which is helpful :).

**Comment by tywmick** [comment]
Closed by open-vsx/publish-extensions#289 😊
