### ISSUE TITLE
Why is this not sorting?

### ISSUE THREAD

**Issue by k-byun** [richie5um/vscode-sort-json#40]
```
[
    {
        "destination": {
            "id": "xx-abc-b-diskuse01"
        }
    },
    {
        "destination": {
            "id": "xx-abc-b-diskalloc01"
        }
    }
]
```

**=> diskalloc01 should appear first but it doesn't.**

**Comment by k-byun** [comment]
Ruling out the string length to troubleshoot - this also does not sort:
![image](https://user-images.githubusercontent.com/72177353/96787846-ad24b280-13af-11eb-8781-c5bfda49438b.png)
`[
    {
        "destination": {
            "id": "xx-abc-b-diskuse01"
        }
    },
    {
        "destination": {
            "id": "xx-abc-b-diskall01"
        }
    }
]`

**Comment by richie5um** [comment]
Hi. The extension doesn’t rearrange array positions - instead it only rearranges keys as they has no impact on the meaning of the JSON.

**Comment by k-byun** [comment]
Good to know.  I am using notepad++ to compare two JSON files but because the same content is positioned in different positions of within the same array in two different files, it's being detected as difference.   Figured sorting both version would align and sort out this so I found your tool to pre-process this in vs code, then pass it to notepad++ - _there might be a simpler process which I am not aware of_.  

I may make a pull request of your add-on extension to implement this later this week/month.
Thank you

**Comment by richie5um** [comment]
Hi. Array sorting is not something this extension is designed for - if you want an array sorting extension then that should be a separate extension :). Array position order has meaning, dictionary key order doesn’t. 

For your specific needs, if array position does not have meaning, then it may be easier for you to write a super simple JavaScript script to read in the file, sort the arrays in code, and write out the sorted arrays for comparison.

**Comment by k-byun** [comment]
Agreed.  That's what I will do.  Thanks!

**Comment by FlorianWendelborn** [comment]
@richie5um @k-byun I think this can be closed
