### ISSUE TITLE
Don't remove quotes from keys

### ISSUE THREAD

**Issue by gmccullo** [richie5um/vscode-sort-json#41]
Sorting strips quotes off property keys. That's an error.

> All property names must be surrounded by double quotes. ~ [Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml)

**Comment by richie5um** [comment]
When the quotes are stripped on using sort-json, that usually means your JSON is not itself strict JSON (as-in, not strict according to the internal JSON parser) - I've included two parser which means you can sort JavaScript JSON (aka without quotes and with comments etc...).

Can you post an example of the JSON you are trying to sort here?

Thanks.

**Comment by gmccullo** [comment]
I used it to sort my settings file. I would argue the extensions should not alter the keys _regardless_. Anyway here's a minimum repro:

BEFORE:

```json
{
	"editor.rulers": [
		{
			"color": "#eee",
			"column": 20
		},
	],
	"todo-tree.general.tags": [
		"BUG:",
	],
}
```

AFTER:

```json
{
    "editor.rulers": [
        {
            color: "#eee",
            column: 20
        }
    ],
    "todo-tree.general.tags": [
        "BUG:"
    ]
}
```

**Comment by richie5um** [comment]
Hmm.. That does look wrong. Let me take a look. Thanks.

**Comment by richie5um** [comment]
The problem is the trailing commas. Looks like that breaks the built-in JSON parser.

This works fine for me...
`{
    "editor.rulers": [
        {
            "color": "eee",
            "column": 20
        }
    ],
    "todo-tree.general.tags": [
        "BUG:"
    ]
}`

**Comment by richie5um** [comment]
FWIW, I do plan at some point to switch over to a different parser (that can handle things like this, and comments) - the babel parser seemed best last time I looked. But, I've not had time to do the work :-|.

**Comment by richie5um** [comment]
New parser implemented.
