### ISSUE TITLE
Feature Request: Add files to ignore

### ISSUE THREAD

**Issue by sri352** [richie5um/vscode-sort-json#43]
Can we have a setting added where we can specify the files for which the sortJSON can be ignored. This is coming after me adding codeActionsOnSave enabled but don't want it to run on package.json and some other limited files.

**Comment by JerryGreen** [comment]
Yeah, I think there should be probably some explicit rules regarding sorting files like `package.json`, something like "importance order", with name first, then description, version, etc. Well, at least in some ideal world. But I'm ok with what it does already, actually
