### ISSUE TITLE
Default to Sort Entire Document if No Selection

### ISSUE THREAD

**Issue by Antyos** [richie5um/vscode-sort-json#48]
Although not a huge deal, I think it would be a nice addition to default to sorting an entire `json` document if there is nothing selected. For new users who don't necessarily read the documentation (like myself...) noting the extension formats based on selection, it would be especially helpful.

This could either be implemented by:
1. Adding commands to differentiate sorting the selection or sorting the document, such as **Sort JSON Document** and **Sort JSON Selection**
2. Default **Sort JSON** to sort the document if there is no selection, otherwise sort the selection
3. Some combination of the previous two

**Comment by Shuunen** [comment]
@Antyos @NorthboundTrain @diartyz I mangaged to have this feature with a new vscode keybind : 

```json
  {
    "command": "sortJSON.sortJSON",
    "key": "ctrl+s",
    "when": "editorTextFocus && !editorReadonly && resourceExtname == .json"
  }
```

Hope it helps 👍

**Comment by richie5um** [comment]
Nice :)
