### ISSUE TITLE
feature request: sort portion of JSON

### ISSUE THREAD

**Issue by alanlivio** [richie5um/vscode-sort-json#57]
It would be interest sort a portion of valid json.
Today the sort, even if a selection, must be a valid json.
For instance, I would like to sort only the fields C, B, A bellow.
```json
{
  "C":  "value",
  "B":  "value",
  "A":  "value",
  "NotImportant":  "value",
}
```

**Comment by richie5um** [comment]
Good idea, but that feels impractical (aka, very difficult ;-)) - but let me know if you have any ideas. 

When I have this, I just use the simple ‘sort lines’ extension.

**Comment by alanlivio** [comment]
Hi @richie5um. Thank you for your answer.
> When I have this, I just use the simple ‘sort lines’ extension.
My problem is when the is arrais objects. 
For instance, I would like to sort only the C, B, A bellow.

```json
{
  "C":  "value",
  "B": {
     "BC":  "value",
     "BB":  "value",
     "BA":  "value",
   }
  "A":  "value",
  "NotImportant":  "value",
}
```

**Comment by alanlivio** [comment]
I understand the difficulty of this and I close the issue.

**Comment by ian-h-chamberlain** [comment]
Hi, I had the idea to try just wrapping the selection in `{}` and sort that, and it seems to work! I opened a draft PR #74 to add this feature to the extension if you are interested.
