### ISSUE TITLE
Doesn't seem to sort keys nested at lower levels inside arrays

### ISSUE THREAD

**Issue by jlucktay** [richie5um/vscode-sort-json#6]
I like the look of this extension but it looks like it doesn't do what I'm after.
I'm hoping to use it on some Azure RM templates to alphabetise the whole thing, so that comparing generated vs hand-written/edited is much more straightforward, and check-ins and diffs and such will be cleaner.
It does not alphabetise inside the "resources" array though, which forms the bulk of ARM JSON templates.

I've attached an example template. You can see the start of the resources array on line 97.
It seems like it doesn't drill down on elements inside that array.
Should it?
Did I miss a config switch somewhere?

[template.json.txt](https://github.com/richie5um/vscode-sort-json/files/803635/template.json.txt)

**Comment by richie5um** [comment]
Hi,

I thought that was working. Let me take a look.

Regards,
-Rich

**Comment by jlucktay** [comment]
Thanks!

**Comment by richie5um** [comment]
I've just published v1.8.0 which should now iterate into arrays (and sort any object properties within). Please let me know if this doesn't work for you. Thanks.
