### ISSUE TITLE
Can this extension sort on a certain value (like displayName in this example)

### ISSUE THREAD

**Issue by jamilhaddadin** [richie5um/vscode-sort-json#61]
can this add-in sort this JSON?
![image](https://user-images.githubusercontent.com/9879719/148958525-e865201c-0244-4098-97e5-6b6c88ce6e65.png)

**Comment by richie5um** [comment]
It can't.

That is because you want to sort an array based on a property - because you are sorting an array, you are changing the meaning of the JSON. Sort-JSON aims to preserve the meaning of the JSON, but make it better organized (which is especially useful for source-control diffs).
