### ISSUE TITLE
Sort by alphanumeric but stick "id" in first position

### ISSUE THREAD

**Issue by heyomi** [richie5um/vscode-sort-json#67]
Is it possible to sort by alphanum but then keep my "id" field in the first position

**Comment by richie5um** [comment]
This should be possible - but I've not tried it. Set the overrides to contain 'id'.

https://github.com/richie5um/vscode-sort-json#settings

**Comment by heyomi** [comment]
Thanks @richie5um This worked.
```
"sortJSON.orderOverride": [
    "id"
  ]
```
