### ISSUE TITLE
[BUG] The elements in an array aren't sorted

### ISSUE THREAD

**Issue by cateyes99** [richie5um/vscode-sort-json#68]
Say I have a JSON doc as below
``` JSON
{
    "productInstanceIds": [
        "dee3265d-2d4a-47d3-d058-306f638391f3",
        "b48af1e0-ba0f-7dd4-ba36-f4810da88b75",
        "fc592fba-c453-e0b6-f2ba-b02a13c1c6de"
    ],
    "path": "22ccef63-5fbf-430c-a1db-6d4f28ff6ecd",
    "id": "22ccef63-5fbf-430c-a1db-6d4f28ff6ecd"
}
```

After running the command `Sort JSON`, I expect it results in the below one:
``` JSON
{
    "id": "22ccef63-5fbf-430c-a1db-6d4f28ff6ecd",
    "path": "22ccef63-5fbf-430c-a1db-6d4f28ff6ecd",
    "productInstanceIds": [
        "b48af1e0-ba0f-7dd4-ba36-f4810da88b75",
        "dee3265d-2d4a-47d3-d058-306f638391f3",
        "fc592fba-c453-e0b6-f2ba-b02a13c1c6de"
    ]
}
```

But the actual resulted one is this:
``` JSON
{
    "id": "22ccef63-5fbf-430c-a1db-6d4f28ff6ecd",
    "path": "22ccef63-5fbf-430c-a1db-6d4f28ff6ecd",
    "productInstanceIds": [
        "dee3265d-2d4a-47d3-d058-306f638391f3",
        "b48af1e0-ba0f-7dd4-ba36-f4810da88b75",
        "fc592fba-c453-e0b6-f2ba-b02a13c1c6de"
    ]
}
```

**Note**: The array **_productInstanceIds_** isn't sorted in the result! But the rest is sorted as expected.

**Comment by richie5um** [comment]
Hi. Yes, this is working as expected. SortJSON aims to make the JSON easier to read, but avoids making data modifications. Changing the order of an array is a data modification.

**Comment by cateyes99** [comment]
@richie5um, apparently why I'm interested in sorted JSONs, one most important thing is that I'd like to compare JSONs, so sorting JSONs comes handy. What about offering a flag to include sorting arrays if you don't want it by default?
