### ISSUE TITLE
Highlighted subset sort

### ISSUE THREAD

**Issue by dyst5422** [richie5um/vscode-sort-json#7]
Often, I will have a subset of JSON that I want to alphabetically sort - say the rules in my eslintrc file - but I want to leave the higher structure unchanged. Hopefully support for sorting a highlighted section of JSON can be added.

**Comment by richie5um** [comment]
Erm, I thought that used to work. I'll look into it.

**Comment by richie5um** [comment]
I have a provisional working version of this now. The re-indent logic doesn't quite work, but, it'll sort just the section - even if that is an embedded JSON property.

To workaround for now, make sure the JSON sub-section you want to sort starts/ends on its own line. The current version grabs whatever text is on the entire lines of those selected, not just the selected section.

I'll do some more testing and get a new update out as soon as I can.

Thanks for the bug report.

**Comment by richie5um** [comment]
I've published 1.9.0. Please let me know if you encounter any issues.
