### ISSUE TITLE
Keys missing the double quotes after sorting

### ISSUE THREAD

**Issue by viniciusmelquiades** [richie5um/vscode-sort-json#8]
I tried sorting my vscode's settings.json file, but I encountered a small problem.

The block that was
```JSON
// ...
"search.exclude":  {
	".git": true,
	"node_modules": true,
	"bower_components": true,
	"packages": true,
	"**/bin": true,
	"**/obj": true
},
// ...
```

But after the sort it was
```JSON
// ...
"search.exclude": {
    "**/bin": true,
    "**/obj": true,
    ".git": true,
    bower_components: true,
    node_modules: true,
    packages: true
},
// ...
```

As you can see, the double quotes are missing for the keys *bower_components*, *node_modules* and *packages*. 

I think the extension got lost at the first key with underline and gave up entirely.
The rest of the file was OK.

**Comment by richie5um** [comment]
Thanks. Can you attach the entire settings.json file and I'll try it on my system?

Regards,
Rich

**Comment by viniciusmelquiades** [comment]
I no longer have the original file, but as I've tested just now if you change the order of the `search.exclude` elements, you should be able to reproduce the problem.

Anyway, this is my current file.

```JSON
{
	"editor.detectIndentation": true,
	"editor.fontFamily": "Fira Code",
	"editor.fontLigatures": true,
	"editor.fontSize": 15,
	"editor.formatOnSave": true,
	"editor.formatOnType": true,
	"editor.glyphMargin": true,
	"editor.insertSpaces": false,
	"editor.minimap.enabled": true,
	"editor.quickSuggestions": true,
	"editor.renderWhitespace": "boundary",
	"editor.wordBasedSuggestions": false,
	"editor.wordWrap": "on",
	"editor.wrappingIndent": "indent",
	"files.autoSave": "off",
	"files.trimTrailingWhitespace": true,
	"git.autofetch": false,
	"search.exclude": {
		"**/bin": true,
		"**/obj": true,
		".git": true,
		"bower_components": true,
		"node_modules": true,
		"packages": true
	},
	"terminal.external.windowsExec": "powershell.exe",
	"terminal.integrated.shell.windows": "powershell.exe",
	"typescript.referencesCodeLens.enabled": true,
	"vsicons.dontShowNewVersionMessage": true,
	"window.reopenFolders": "none",
	"window.zoomLevel": 0,
	"workbench.welcome.enabled": true,
	"workbench.iconTheme": "vscode-icons"
}
```

**Comment by richie5um** [comment]
I've managed to reproduce, but only if the JSON is invalid.

If you add a comma to the end of the line: "packages": true
Then sort, it'll remove the double quotes for some of the entries.

This is kinda a feature, as SortJSON will handle quoted and non-quoted properties names - and output accordingly. It does this by running through two different JSON parsers. However, in this instance, you can getting a mixed output.

I'll investigate, but, suspect the problem will only surface if the JSON is not 100% valid. Does this sound like it maps to the scenario you've seen?

**Comment by viniciusmelquiades** [comment]
Well, I had a comments before the opening bracket in the file. You could try testing with that. I still don't know why only the "search.exclude" object went nuts and not the whole file.

**Comment by richie5um** [comment]
Ah, that explains why the JSON isn't parsing. I'll look into why it causes and issue to just that section.

**Comment by 0x80** [comment]
Ran into the same issue with this json file:

```
{
  // TODO:
  // 	Restrict access to all resources
  // 	https://github.com/firebase/bolt
  // 	https://github.com/firebase/bolt/blob/master/docs/guide.md

  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",

    "emails": {
      ".indexOn": ["to/uid"]
    },

    "firebase-queue": {
      "signup-flow": {
        "user-signup": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        },
        "airline-info": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        },
        "corporate-badge": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        },
        "user-signup-details": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        },
        "verification-result": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        },
        "store-facebook-data": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        }
      },
      "requests": {
        "create-request": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        }
      },
      "responses": {
        "create-response": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        }
      },
      "user-settings": {
        "fcm": {
          "tasks": {
            ".indexOn": ["_state"]
          }
        }
      }
    }
  }
}
```

**Comment by 0x80** [comment]
Ah the issue here is that this JSON is also invalid because of the comments. Its confusing that a lot of tools accept invalid JSON like this. But it would be nice if the plugin could handle these kind of things somehow.

**Comment by richie5um** [comment]
Ah. I understand now. This is because the extension uses the default JSON parser to start with, if that fails, it tries the JSON5 parser which allows non-quoted keys. Whichever parser works, it used for the output - hence why it is stripping the quotes.

I will look to see if the JSON5 parser can be forced to output in JSON format (i.e. with the quotes).

**Comment by 0x80** [comment]
I think it would be ok to strip the comments and output valid JSON. I'd rather have comments disappear from shitty formatted JSON then have the plugin produce something that no tool can consume anymore.

**Comment by richie5um** [comment]
Give me a few hours, I’ll see what I can cook up.

**Comment by richie5um** [comment]
Try updating the extension :).

**Comment by mikerockett** [comment]
This is still happening on my side with a fresh install of the extension (for the first time). Could it perhaps have something to do with periods in the keys? (As a test, I'm sorting my vscode settings file.)

**Comment by richie5um** [comment]
Does it still happen with the json file you included earlier on this thread?

**Comment by mikerockett** [comment]
@richie5um This is the first time I've posted here...

**Comment by GammaGames** [comment]
I tried sorting my settings file and it is still occurring. It seems to happen for nested key value pairs

**Comment by richie5um** [comment]
Thanks. Can you post an example json and I’ll see if it is fixable?

**Comment by GammaGames** [comment]
Here's some lines that do it:

```json
// Place your settings in this file to overwrite the default settings
{
    "todohighlight.defaultStyle": {
        "color": "#FF2D00",
        "backgroundColor": "#111",
        "border": "1px solid #343434",
        "isWholeLine": true
    }
}
```

The output is:
```json
{
    "todohighlight.defaultStyle": {
        backgroundColor: "#111",
        border: "1px solid #343434",
        color: "#FF2D00",
        isWholeLine: true
    }
}
```

**Comment by reporter123** [comment]
I just discover the source of this problem.
`  if ((/^\s+\/\/.*$/.test(text))) {`
This regexp does not match comments with no space in front of them or if the comment is attached to a line as in:
```
//no don't just install things for me.
"extensions.autoUpdate": false,
```
or
`"extensions.autoUpdate": false,//no don't just install things for me.`

**Comment by richie5um** [comment]
Perfect. Thanks. I'll look at the regexp - unless you already have a solution?!

**Comment by reporter123** [comment]
I think so working on it now. I purposely don't cover "// as this is ambiguous i.e could be part of a string from our stand point.

**Comment by mariomeissner** [comment]
Hi! The following `settings.json` still removes quotes for me: 

```
{
    "editor.fontFamily": "mononoki, Consolas, 'Courier New', monospace",
    "editor.fontSize": 15,
    "editor.formatOnSave": true,
    "editor.minimap.maxColumn": 80,
    "editor.quickSuggestions": {
        "comments": false,
        "other": true,
        "strings": false
    },
    "editor.suggest.localityBonus": true,
    "editor.suggestOnTriggerCharacters": true,
    "editor.suggestSelection": "recentlyUsedByPrefix",
    "explorer.confirmDelete": false,
    "git.autofetch": true,
    "git.confirmSync": false,
    "python.dataScience.allowLiveShare": true,
    "python.dataScience.errorBackgroundColor": "#1e1e1e",
    "python.dataScience.sendSelectionToInteractiveWindow": true,
    "python.formatting.blackArgs": [
        "-l",
        "90"
    ],
    "python.formatting.provider": "yapf",
    "python.linting.enabled": true,
    "python.linting.flake8Args": [
        "--max-line-length",
        "90",
        "--ignore",
        "E302,E501,W503,E203,F401"
    ],
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.gist": "f7e671719f212c7c26ed91f15c1c50fa",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "vim.easymotion": true,
    "vim.insertModeKeyBindings": [
        {
            "after": [
                "<Esc>"
            ],
            "before": [
                "j",
                "j"
            ]
        }
    ],
    "vim.normalModeKeyBindings": [
        {
            "after": [
                "leader",
                "leader",
                "leader",
                "b",
                "d",
                "w"
            ],
            "before": [
                " "
            ]
        }
    ],
    "vim.visualModeKeyBindings": [
        {
            "after": [
                ">",
            ],
            "before": [
                "<Tab>"
            ]
        },
        {
            "after": [
                "<",
            ],
            "before": [
                "<S-Tab>"
            ]
        },
    ],
    "vim.sneak": true,
    "vim.sneakUseIgnorecaseAndSmartcase": true,
    "vim.surround": true,
    "vim.useCtrlKeys": false,
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Material Theme Darker",
    "files.autoSave": "afterDelay"
}
```

**Comment by Robula** [comment]
@richie5um This is still an issue, happening consistently.

Thanks

**Comment by richie5um** [comment]
I’ll take a look.

**Comment by richie5um** [comment]
@mariomeissner There are some trailing commas in that JSON - that causes issues for a (strict) JSON parser, which causes the output issues. If you remove those commas, then it works correctly. Like this...

{
    "editor.fontFamily": "mononoki, Consolas, 'Courier New', monospace",
    "editor.fontSize": 15,
    "editor.formatOnSave": true,
    "editor.minimap.maxColumn": 80,
    "editor.quickSuggestions": {
        "comments": false,
        "other": true,
        "strings": false
    },
    "editor.suggest.localityBonus": true,
    "editor.suggestOnTriggerCharacters": true,
    "editor.suggestSelection": "recentlyUsedByPrefix",
    "explorer.confirmDelete": false,
    "files.autoSave": "afterDelay",
    "git.autofetch": true,
    "git.confirmSync": false,
    "python.dataScience.allowLiveShare": true,
    "python.dataScience.errorBackgroundColor": "#1e1e1e",
    "python.dataScience.sendSelectionToInteractiveWindow": true,
    "python.formatting.blackArgs": [
        "-l",
        "90"
    ],
    "python.formatting.provider": "yapf",
    "python.linting.enabled": true,
    "python.linting.flake8Args": [
        "--max-line-length",
        "90",
        "--ignore",
        "E302,E501,W503,E203,F401"
    ],
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.gist": "f7e671719f212c7c26ed91f15c1c50fa",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "vim.easymotion": true,
    "vim.insertModeKeyBindings": [
        {
            "after": [
                "<Esc>"
            ],
            "before": [
                "j",
                "j"
            ]
        }
    ],
    "vim.normalModeKeyBindings": [
        {
            "after": [
                "leader",
                "leader",
                "leader",
                "b",
                "d",
                "w"
            ],
            "before": [
                " "
            ]
        }
    ],
    "vim.sneak": true,
    "vim.sneakUseIgnorecaseAndSmartcase": true,
    "vim.surround": true,
    "vim.useCtrlKeys": false,
    "vim.visualModeKeyBindings": [
        {
            "after": [
                ">"
            ],
            "before": [
                "<Tab>"
            ]
        },
        {
            "after": [
                "<"
            ],
            "before": [
                "<S-Tab>"
            ]
        }
    ],
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Material Theme Darker"
}

**Comment by yzhang-gh** [comment]
I just had the same issue.

I see that there may be some differences between _the VSCode's JSON with comments_ and _strict JSON format_, which causes this bad output.
But usually, users have big `settings.json` files and are probably not aware of whether there are some easy-to-break parts (e.g. comments).

One solution is to relax the strict JSON format, which you already discussed.

But I have an idea from a different angle, **how about doing a quick check** (e.g. whether there are comments, unexpected trailing commas in the JSON, etc.) **and popping up a warning/confirmation before the formatting**.

**Comment by mariomeissner** [comment]
I agree that at the very least, instead of breaking the file it should warn
the user and not perform the operation.

**Comment by parkerault** [comment]
I installed this extension explicitly to sort my vscode settings.json and have the same issue. Every key more than one level deep loses its quotes. I imagine this is a pretty common use case, and vscode settings use the `jsonc` language setting (it also accepts ES6-style trailing commas). I echo the sentiment above; my default assumption would be that invalid JSON would fail to format, not format incorrectly.

**Comment by Spenhouet** [comment]
I also installed this extension to sort my `settings.json` in vscode.
VS code does not add trailing commas. You are suggesting that that is not valid JSON. Why? I actually never heard of that rule. In fact, most automatic formatting tools remove the trailing commas. I would suggest that that should not be a rule that this extension should rely on. It should work without trailing commas.

**Comment by richie5um** [comment]
Sorting now handles comments (JSONC) in the latest version.
